version: '3.9'
services:
  app:
    tty: true
    build: .
    expose:
      - 8080
    scale: 3
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: "apartments"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  nginx:

    container_name: nginx
    image: nginx:latest
    # build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/home/static
    ports:
      - 81:81
    depends_on:
      - app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pds@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pg_data:
  static_volume:
  pgadmin-data:
